--CRIA UM BANCO DE DADOS
CREATE DATABASE Teste;

--USA O BANCO DE DADOS
USE Teste;

--CRIA UMA TABELA
CREATE TABLE Funcionarios
( Idfuncionario INT PRIMARY KEY IDENTITY,
  nome VARCHAR (100)
)

--EXCLUI A COLUNA
ALTER TABLE Funcionarios
DROP COLUMN nome;

--EXCLUI A TABELA
DROP TABLE funcionarios;

--EXCLUI O BANCO DE DADOS
DROP DATABASE Teste;