
CREATE DATABASE Exercicio1_4

USE Exercicio1_4

CREATE TABLE Artistas(
IdArtista INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR (15) NOT NULL
)

CREATE TABLE Estilos(
IdEstilo INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR (20) NOT NULL
)

CREATE TABLE Albuns(
IdAlbum INT PRIMARY KEY IDENTITY,
IdArtista INT FOREIGN KEY REFERENCES Artistas(IdArtista),
IdEstilo INT FOREIGN KEY REFERENCES Estilos(IdEstilo),
Titulo VARCHAR (20) NOT NULL,
DataLancamento DATE NOT NULL,
QDeMinutos FLOAT NOT NULL,
Ativo BIT  
)

CREATE TABLE Usuarios(
IdUsuario INT PRIMARY KEY IDENTITY,
Nome VARCHAR (20) NOT NULL,
Email VARCHAR (30)NOT NULL,
Senha VARCHAR (10)NOT NULL,
Permissao Bit

)



DROP TABLE Usuarios